### PR TITLE
Make mode line indicator customizable

### PR DESCRIPTION
**Pull request by peniblec**
Largely inspired by Magit's lighters, eg for [magit-blame-mode].

Thank you for this package! I like it so much I basically enabled it as globally as I could (ie for fundamental, text, prog and special modes).

(First pull request ever, let me know if I am doing something wrong)

[magit-blame-mode]: https://github.com/magit/magit/blob/4a3d777226c2bec72a9b025ca4d4bdb69c15765b/lisp/magit-blame.el#L77-L80

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! I'll merge this, but I'd generally suggest that people use `diminish` to customize or remove minor mode modeline indicators.

**Comment by xiongtx** [comment]
How'd we end up with `PgLn` and not `^L`? :stuck_out_tongue:

**Comment by purcell** [comment]
> How'd we end up with PgLn and not ^L? 😛

Both are a bit ugly, I think. Personally I prefer to completely `diminish` this minor mode. :-)

**Comment by peniblec** [comment]
> Personally I prefer to completely `diminish` this minor mode. :-)

I have to admit that `diminish` does the job perfectly, as I found out literally minutes after you merged this PR. I had no idea this package existed at the time, so thank you for mentioning it!

(On the plus side, I am glad I discovered it, since its "codeprose" was a joy to read. On the minus side, now I have a permanent TODO item in my `.emacs` asking me to review `diminish`, `dim`, `rich-minority` and `delight` to figure out which one is "optimal", whatever that's supposed to mean)

**Comment by purcell** [comment]
> On the minus side, now I have a permanent TODO item in my .emacs asking me to review diminish, dim, rich-minority and delight to figure out which one is "optimal", whatever that's supposed to mean)

Haha, I know that feeling. But if you don't know why you need anything but `diminish`, then `diminish` is probably all you need. :-)

**Pull request merged**
